# Generated by Django 6.0.6 on 2026-06-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopknockingbullet',
            name='page',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='cta_description',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='cta_title',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='cta_whatsapp_link',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='hero_cta_link',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='hero_cta_text',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='hero_description',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='usp_badge',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='usp_badge_text',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='usp_description_1',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='usp_description_2',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='usp_image',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='usp_title',
        ),
        migrations.DeleteModel(
            name='WorkshopGalleryImage',
        ),
        migrations.DeleteModel(
            name='WorkshopKnockingBullet',
        ),
    ]
