# Generated by Django 6.0.6 on 2026-06-16 01:44

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('workshop', '0002_remove_workshopknockingbullet_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoppage',
            name='cta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='cta_title',
            field=models.TextField(default='Does Your Bat\nNeed Attention?'),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='cta_whatsapp_link',
            field=models.CharField(default='https://wa.me/60123456789', max_length=255),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='hero_cta_link',
            field=models.CharField(default='https://wa.me/60123456789', max_length=255),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='hero_cta_text',
            field=models.CharField(default='Book a Service', max_length=100),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='hero_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='hero_title',
            field=models.TextField(default='Expert Care.\nPeak Performance.'),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='usp_badge',
            field=models.CharField(default='Exclusive', max_length=100),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='usp_badge_text',
            field=models.CharField(default='The Only Knocking Machine in JB', max_length=255),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='usp_description_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='usp_description_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='usp_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='usp_title',
            field=models.TextField(default='Ready for\nMatch Play.'),
        ),
        migrations.CreateModel(
            name='WorkshopGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='workshop.workshoppage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkshopKnockingBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('bullet_text', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='usp_bullets', to='workshop.workshoppage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
