# Generated by Django 6.0.6 on 2026-06-16 04:09

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('workshop', '0003_workshoppage_cta_description_workshoppage_cta_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopknockingbullet',
            name='page',
        ),
        migrations.RemoveField(
            model_name='workshopservice',
            name='page',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='cta_description',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='cta_title',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='cta_whatsapp_link',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='hero_cta_link',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='hero_cta_text',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='hero_description',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='usp_badge',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='usp_badge_text',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='usp_description_1',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='usp_description_2',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='usp_image',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='usp_title',
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.CreateModel(
            name='WorkshopGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('video_url', models.URLField(blank=True, help_text='Optional: Enter a video URL. If provided, this item will render as a video in the gallery.', max_length=500)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='workshop.workshoppage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='WorkshopGalleryImage',
        ),
        migrations.DeleteModel(
            name='WorkshopKnockingBullet',
        ),
        migrations.DeleteModel(
            name='WorkshopService',
        ),
    ]
