# Generated by Django 6.0.6 on 2026-06-15 17:46

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageOperatingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('day', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePagePillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('icon_name', models.CharField(help_text='e.g. Package, Hammer, Wrench, Swords, Users', max_length=100)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('val', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageWhyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('card_number', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('video_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_subtitle', models.CharField(default='Johor Bahru · Malaysia', max_length=255)),
                ('hero_title', models.TextField(default='WHERE\nCRICKET\nGETS\nSERIOUS.')),
                ('hero_description', models.TextField(blank=True)),
                ('hero_primary_cta_text', models.CharField(default='Visit Our Store', max_length=100)),
                ('hero_primary_cta_link', models.CharField(default='/contact', max_length=255)),
                ('hero_secondary_cta_text', models.CharField(default='Contact Us', max_length=100)),
                ('hero_secondary_cta_link', models.CharField(default='https://wa.me/60123456789', max_length=255)),
                ('custom_bats_title', models.TextField(default='Crafted\nTo Your\nGame.')),
                ('custom_bats_description', models.TextField(blank=True)),
                ('custom_bats_primary_cta_text', models.CharField(default='Start Your Order', max_length=100)),
                ('custom_bats_primary_cta_link', models.CharField(default='/custom-bats', max_length=255)),
                ('custom_bats_secondary_cta_text', models.CharField(default='Ask Us', max_length=100)),
                ('custom_bats_secondary_cta_link', models.CharField(default='https://wa.me/60123456789', max_length=255)),
                ('custom_bats_tags', models.CharField(default='English Willow, Kashmir Willow, Custom Weight, Handle Preference, Grip Selection', max_length=500)),
                ('visit_title', models.CharField(default='Come See Us In Johor Bahru.', max_length=255)),
                ('visit_address', models.TextField(default='No. 12, Jalan Perang,\nTaman Perang,\n80150 Johor Bahru, Johor.')),
                ('visit_phone', models.CharField(default='+60 7-334 5678', max_length=100)),
                ('visit_whatsapp', models.CharField(default='https://wa.me/60123456789', max_length=255)),
                ('visit_directions_link', models.CharField(default='https://maps.google.com', max_length=255)),
                ('footer_text', models.TextField(default="Johor Bahru's premier cricket destination. Equipment, training, and expertise for every player.")),
                ('footer_address', models.TextField(default='No. 12, Jalan Perang\nTaman Perang, 80150\nJohor Bahru, Johor')),
                ('footer_phone', models.CharField(default='+60 7-334 5678', max_length=100)),
                ('footer_email', models.CharField(default='hello@mrwillow.my', max_length=100)),
                ('footer_whatsapp', models.CharField(default='https://wa.me/60123456789', max_length=255)),
                ('footer_copyright', models.CharField(default='© 2024 MR.WILLOW Cricket Store. All rights reserved.', max_length=255)),
                ('custom_bats_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('visit_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePageFeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_products', to='homepage.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
