# Generated by Django 6.0.6 on 2026-06-15 17:46

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
        ('products', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagefeaturedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.product'),
        ),
        migrations.AddField(
            model_name='homepageoperatinghour',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='homepage.homepage'),
        ),
        migrations.AddField(
            model_name='homepagepillar',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pillars', to='homepage.homepage'),
        ),
        migrations.AddField(
            model_name='homepagestat',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_stats', to='homepage.homepage'),
        ),
        migrations.AddField(
            model_name='homepagewhycard',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepagewhycard',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_cards', to='homepage.homepage'),
        ),
    ]
