# Generated by Django 6.0.6 on 2026-06-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_homepagestat_page_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageFeaturedProduct',
        ),
    ]
