# Generated by Django 6.0.6 on 2026-06-16 01:44

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_delete_homepagefeaturedproduct'),
        ('products', '0002_product_is_featured'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='custom_bats_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_bats_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_bats_primary_cta_link',
            field=models.CharField(default='/custom-bats', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_bats_primary_cta_text',
            field=models.CharField(default='Start Your Order', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_bats_secondary_cta_link',
            field=models.CharField(default='https://wa.me/60123456789', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_bats_secondary_cta_text',
            field=models.CharField(default='Ask Us', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_bats_tags',
            field=models.CharField(default='English Willow, Kashmir Willow, Custom Weight, Handle Preference, Grip Selection', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_bats_title',
            field=models.TextField(default='Crafted\nTo Your\nGame.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_address',
            field=models.TextField(default='No. 12, Jalan Perang\nTaman Perang, 80150\nJohor Bahru, Johor'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_copyright',
            field=models.CharField(default='© 2024 MR.WILLOW Cricket Store. All rights reserved.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_email',
            field=models.CharField(default='hello@mrwillow.my', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_phone',
            field=models.CharField(default='+60 7-334 5678', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_text',
            field=models.TextField(default="Johor Bahru's premier cricket destination. Equipment, training, and expertise for every player."),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_whatsapp',
            field=models.CharField(default='https://wa.me/60123456789', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_cta_link',
            field=models.CharField(default='/contact', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_cta_text',
            field=models.CharField(default='Visit Our Store', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_cta_link',
            field=models.CharField(default='https://wa.me/60123456789', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_cta_text',
            field=models.CharField(default='Contact Us', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(default='Johor Bahru · Malaysia', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.TextField(default='WHERE\nCRICKET\nGETS\nSERIOUS.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visit_directions_link',
            field=models.CharField(default='https://maps.google.com', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visit_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visit_title',
            field=models.CharField(default='Come See Us In Johor Bahru.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visit_whatsapp',
            field=models.CharField(default='https://wa.me/60123456789', max_length=255),
        ),
        migrations.CreateModel(
            name='HomePageFeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_products', to='homepage.homepage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.product')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePagePillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('icon_name', models.CharField(help_text='e.g. Package, Hammer, Wrench, Swords, Users', max_length=100)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pillars', to='homepage.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('val', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_stats', to='homepage.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
