# Generated by Django 6.0.6 on 2026-06-16 04:09

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_homepage_custom_bats_description_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageoperatinghour',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepagepillar',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepagestat',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepagewhycard',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepagewhycard',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='custom_bats_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='custom_bats_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='custom_bats_primary_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='custom_bats_primary_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='custom_bats_secondary_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='custom_bats_secondary_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='custom_bats_tags',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='custom_bats_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='footer_address',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='footer_copyright',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='footer_email',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='footer_phone',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='footer_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='footer_whatsapp',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_primary_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_primary_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_secondary_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_secondary_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='visit_address',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='visit_directions_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='visit_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='visit_phone',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='visit_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='visit_whatsapp',
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_text', models.CharField(default='✦  Free Bat Knocking With Every Bat Purchase  ·  Visit Us In Johor Bahru  ✦', max_length=255)),
                ('whatsapp_number', models.CharField(default='+60 12-345 6789', max_length=50)),
                ('whatsapp_url', models.CharField(default='https://wa.me/60123456789', max_length=255)),
                ('phone', models.CharField(default='+60 7-334 5678', max_length=50)),
                ('email', models.CharField(default='hello@mrwillow.my', max_length=100)),
                ('store_name', models.CharField(default='MR.WILLOW Cricket Store', max_length=100)),
                ('address', models.TextField(default='No. 12, Jalan Perang\nTaman Perang, 80150\nJohor Bahru, Johor')),
                ('google_maps_link', models.URLField(default='https://maps.google.com', max_length=500)),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com', max_length=500)),
                ('tiktok_url', models.URLField(blank=True, default='https://tiktok.com', max_length=500)),
                ('youtube_url', models.URLField(blank=True, default='https://youtube.com', max_length=500)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessSettingsOperatingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('day', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('setting', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='homepage.businesssettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='HomePageFeaturedProduct',
        ),
        migrations.DeleteModel(
            name='HomePageOperatingHour',
        ),
        migrations.DeleteModel(
            name='HomePagePillar',
        ),
        migrations.DeleteModel(
            name='HomePageStat',
        ),
        migrations.DeleteModel(
            name='HomePageWhyCard',
        ),
    ]
