# Generated by Django 6.0.6 on 2026-06-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_remove_homepageoperatinghour_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='custom_bat_orders_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable custom bat enquiries site-wide.', verbose_name='Custom Bat Orders Enabled'),
        ),
    ]
