# Generated by Django 6.0.6 on 2026-06-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_businesssettings_custom_bat_orders_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesssettings',
            options={'verbose_name': 'Store Details'},
        ),
    ]
