# Generated by Django 6.0.6 on 2026-06-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_businesssettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='announcement_enabled',
            field=models.BooleanField(default=True, help_text='Show or hide the announcement bar at the very top of the website.', verbose_name='Announcement Enabled'),
        ),
    ]
